# Generated by Django 2.0 on 2018-08-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='capactiy',
            new_name='capacity',
        ),
    ]
