# Generated by Django 2.0 on 2018-08-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180815_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guests',
        ),
    ]
