# Generated by Django 2.0 on 2018-08-15 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180815_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lead_booker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
