# Generated by Django 2.0 on 2018-08-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180820_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ManyToManyField(null=True, to='api.Room'),
        ),
        migrations.RemoveField(
            model_name='room',
            name='bookings',
        ),
        migrations.AddField(
            model_name='room',
            name='bookings',
            field=models.ManyToManyField(null=True, related_name='bookings', to='api.Booking'),
        ),
    ]
