# Generated by Django 2.0 on 2018-08-22 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180822_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='bookings',
        ),
        migrations.AddField(
            model_name='room',
            name='bookings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.Booking'),
        ),
    ]
