# Generated by Django 2.0 on 2018-08-22 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180822_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ManyToManyField(blank=True, to='api.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bookings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.Booking'),
        ),
    ]
