# Generated by Django 2.0 on 2018-08-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180822_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='bookings',
        ),
        migrations.AddField(
            model_name='room',
            name='bookings',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='api.Booking'),
        ),
    ]
